#!/usr/bin/perl
# Helper for caffeine-screensaver to inhibit desktop idleness using freedesktop.org DBus interface
# N.B. This script sleeps forever, so it must be killed to stop the inhibition

use strict;
use warnings;

use Net::DBus;

my $bus = Net::DBus->session;
my $service = $bus->get_service("org.freedesktop.ScreenSaver");
my $manager = $service->get_object("/org/freedesktop/ScreenSaver", "org.freedesktop.ScreenSaver");
$manager->Inhibit("org.freedesktop.xdg-screensaver", "caffeine-screensaver suspend");

# Keep inhibiting until we're killed
sleep;
